### ISSUE TITLE
addon-level compile - error dependencies

### ISSUE THREAD

**Issue by minecraft7net** [BentoBoxWorld/addon-level#16]
Hi i tried to compile addons / level / welcome-sign / challanges - but only bskyblock compile ok

error:

https://pastebin.com/3Xfmw9VL

**Comment by tastybento** [comment]
Yep, the Master branch was old. I've pushed the latest version.

Also, you have to build in a specific order and have them on the same machine/IDE because they have inter-dependence:

1. Build BentoBox (develop branch is latest)
2. Build add-ons BSkyBlock and AcidIsland
3. Build addon-level
4. Build Welcome signs
5. Build Challenges

**Comment by minecraft7net** [comment]
OK prev, BentoBox and BSkyBlock was compiled OK i'll try once again.

BentoBox:  (warning)

[WARNING] Javadoc Warnings
[WARNING] /storage/satastorage1/spigot13/github/20180802/bentobox/bentobox/src/main/java/world/bentobox/bentobox/database/objects/Island.java:267: warning - Tag @link: can't find getIslandDistance() in world.bentobox.bentobox.Settings
[WARNING] /storage/satastorage1/spigot13/github/20180802/bentobox/bentobox/src/main/java/world/bentobox/bentobox/database/objects/Island.java:521: warning - Tag @link: can't find getIslandDistance() in world.bentobox.bentobox.Settings
[WARNING] /storage/satastorage1/spigot13/github/20180802/bentobox/bentobox/src/main/java/world/bentobox/bentobox/managers/IslandWorldManager.java:567: warning - @return tag has no arguments.
[INFO] Building jar: /storage/satastorage1/spigot13/github/20180802/bentobox/bentobox/target/bentobox-FC-0.8-javadoc.jar

**Comment by tastybento** [comment]
You can ignore Javadoc warnings.

**Comment by minecraft7net** [comment]
if i try to compile acid-islands:

https://pastebin.com/6DGY7JGY

**Comment by minecraft7net** [comment]
could you help me with those dependiences and mvn usage?

**Comment by minecraft7net** [comment]
bskyblock - compile ok - with just mvn install
ls target/
bskyblock-FC-0.79.jar

**Comment by minecraft7net** [comment]
what is url for CI Builds latest ?

**Comment by tastybento** [comment]
Yes, just give me some time and we'll do a release that all works. :-)
