### ISSUE TITLE
Death Count Does Not Increase

### ISSUE THREAD

**Issue by FortyEffs** [BentoBoxWorld/addon-level#18]
I've tried dying Opped and not. Can't seem to make the death count budge.
Plugins (14): WorldEdit, BentoBox, PermissionsEx, Vault, WorldGuard, Multiverse-Core, Citizens, ChestShop, Essentials, ChatControl, HeadDatabase, CrateReloaded, EssentialsSpawn, VanishNoPacket

**Comment by tastybento** [comment]
Thanks for the report. I fixed it in a commit to BentoBox. BentoBox was not adding deaths when player's died.
